apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: devboard
data:
  PORT: "8081"
  POSTGRES_URL: "postgres://devboard:devboard@devboard-db-svc:5432/devboard?sslmode=disable"
